export const STORY_PRESETS = [
  {
    id: "johnson",
    label: "Identity Merge",
    shortLabel: "Scenario 01",
    query: "Johnson client",
    caption: "Show how duplicate company records collapse into one clean business identity.",
    focusTitle: "One client, many records, one explainable merge.",
    resultHeading: "Best duplicate candidates",
    guide: [
      "Amber links mark the strongest same_as style merge cues around the selected client.",
      "The ranked list on the left shows which records retrieval believes belong to the same business story.",
      "Click a result and the right rail explains why it won, plus where the source evidence came from.",
    ],
  },
  {
    id: "logistics",
    label: "Logistics Signal",
    shortLabel: "Scenario 02",
    query: "logistics client",
    caption: "Show how hybrid retrieval pulls the right relationship cluster out of a noisy graph.",
    focusTitle: "A business signal gets isolated out of the full network.",
    resultHeading: "Best signal matches",
    guide: [
      "Bright cyan links show the active neighborhood that gives the selected result its context.",
      "The graph fades everything else so the audience can follow one signal instead of the whole database.",
      "Use this when you want to explain how graph and vector retrieval work together on one business question.",
    ],
  },
  {
    id: "vendor",
    label: "Vendor Overlap",
    shortLabel: "Scenario 03",
    query: "vendor same as client",
    caption: "Show where identities collide across roles and where provenance keeps the answer trustworthy.",
    focusTitle: "Overlap gets surfaced without losing the source trail.",
    resultHeading: "Best overlap matches",
    guide: [
      "This scenario is best for showing suspicious overlap between vendors, clients, and neighboring records.",
      "The active node stays bright while the right rail turns the graph pattern into a readable proof chain.",
      "Leave provenance on to land the point that every claim still ties back to an explicit source record.",
    ],
  },
];

export const FALLBACK_PAYLOAD = {
  query: "who is connected to this customer issue",
  requested_mode: "auto",
  mode: "hybrid",
  top_k: 3,
  node_type: null,
  expand_hops: 1,
  related_limit: 6,
  index: {
    documents: 4210,
    unique_terms: 18240,
  },
  results: [
    {
      rank: 1,
      node_id: "Employee:emp_0431",
      node_type: "Employee",
      title: "Raj Patel",
      summary: "department: Engineering | level: Lead | email: raj@inazuma.co",
      mode: "hybrid",
      score: 0.94,
      graph_score: 0.88,
      vector_score: 0.82,
      matched_terms: ["customer", "issue"],
      evidence: [
        "property `department` matched query terms",
        "outgoing `represents_client` to Acme Ltd",
        "outgoing `assigned_ticket` to Laptop login failure",
      ],
      properties: {
        name: "Raj Patel",
        department: "Engineering",
        level: "Lead",
      },
      provenance: [
        {
          source_system: "Human_Resource_Management",
          file: "employees.json",
          record_id: "emp_0431",
          confidence: 1.0,
        },
      ],
      related: [
        {
          direction: "outgoing",
          rel_type: "assigned_ticket",
          node_id: "ITTicket:1842",
          node_type: "ITTicket",
          title: "Laptop login failure",
          summary: "priority: High | assigned date: 2026-04-24",
        },
        {
          direction: "outgoing",
          rel_type: "represents_client",
          node_id: "Client:acme",
          node_type: "Client",
          title: "Acme Ltd",
          summary: "industry: Logistics | poc status: Active",
        },
        {
          direction: "incoming",
          rel_type: "support_by_agent",
          node_id: "SupportChat:sc_13",
          node_type: "SupportChat",
          title: "Billing + delivery escalation",
          summary: "date: 2026-04-22 | customer: ALFKI",
        },
      ],
    },
    {
      rank: 2,
      node_id: "Customer:alfki",
      node_type: "Customer",
      title: "Alfki Retail",
      summary: "category: Enterprise | date of purchase: 2026-04-20",
      mode: "hybrid",
      score: 0.87,
      graph_score: 0.71,
      vector_score: 0.84,
      matched_terms: ["customer", "issue"],
      evidence: [
        "matched within generated stitched entity view",
        "incoming `support_for_customer` from Billing + delivery escalation",
        "outgoing `purchased` to Sale:s_8821",
      ],
      properties: {
        name: "Alfki Retail",
        invoice_path: "invoice_alfki.pdf",
      },
      provenance: [
        {
          source_system: "Customer_Relation_Management",
          file: "customers.json",
          record_id: "alfki",
          confidence: 1.0,
        },
      ],
      related: [
        {
          direction: "incoming",
          rel_type: "support_for_customer",
          node_id: "SupportChat:sc_13",
          node_type: "SupportChat",
          title: "Billing + delivery escalation",
          summary: "date: 2026-04-22 | customer: ALFKI",
        },
        {
          direction: "outgoing",
          rel_type: "purchased",
          node_id: "Sale:s_8821",
          node_type: "Sale",
          title: "Order 8821",
          summary: "date of purchase: 2026-04-20 | product id: p_934",
        },
      ],
    },
    {
      rank: 3,
      node_id: "EmailThread:th_9982",
      node_type: "EmailThread",
      title: "Urgent customer delivery delay",
      summary: "subject: Urgent customer delivery delay | date: 2026-04-23",
      mode: "hybrid",
      score: 0.81,
      graph_score: 0.76,
      vector_score: 0.65,
      matched_terms: ["issue"],
      evidence: [
        "matched within generated stitched entity view",
        "incoming `part_of_thread` from customer escalation email",
      ],
      properties: {
        subject: "Urgent customer delivery delay",
      },
      provenance: [
        {
          source_system: "Enterprise_Mail_System",
          file: "emails.json",
          record_id: "thread:th_9982",
          confidence: 1.0,
        },
      ],
      related: [
        {
          direction: "incoming",
          rel_type: "part_of_thread",
          node_id: "Email:em_331",
          node_type: "Email",
          title: "customer escalation email",
          summary: "importance: high | category: escalation",
        },
        {
          direction: "incoming",
          rel_type: "sent_email",
          node_id: "Employee:emp_0431",
          node_type: "Employee",
          title: "Raj Patel",
          summary: "department: Engineering | level: Lead",
        },
      ],
    },
  ],
  context:
    "[1] Raj Patel (Employee)\nSummary: Engineering lead connected to the active incident\n[2] Alfki Retail (Customer)\nSummary: Customer record with support and order context",
  cognee: {
    available: false,
    reason: "offline_story_mode",
  },
};
